<template>
  <view class="family-page plane-page">
    <view class="plane-heading"><view><text class="eyebrow">MIAO AIR · 经典街机</text><text class="title">纸翼飞行队</text><text class="intro">拖动飞机，自动发射。看准空隙，灵巧避让。</text></view><text class="pilot-mark">✈</text></view>
    <view class="flight-layout"><view class="battle-column"><view class="flight-stats" :style="{width:width+'px'}"><view><text>本局得分</text><text>{{ game.score }}</text></view><view><text>剩余机体</text><text>{{ '♥'.repeat(game.lives) || '—' }}</text></view><view><text>剩余时间</text><text>{{ Math.max(0,90-Math.floor(game.time)) }}s</text></view></view>
      <view class="battle-wrap" :style="{width:width+'px',height:height+'px'}">
        <canvas class="battle" id="plane-stage" canvas-id="plane-stage" :width="width" :height="height" :style="{width:width+'px',height:height+'px'}" :disable-scroll="true" @touchstart="touch" @touchmove.stop.prevent="touch" @mousedown="mouseDown" @mousemove="mouseMove" @mouseup="dragging=false" @mouseleave="dragging=false"/>
        <view v-if="game.status!=='running'" class="flight-overlay"><text class="overlay-emblem">✈</text><text class="overlay-title">{{ statusTitle }}</text><text class="overlay-copy">{{ statusCopy }}</text><button class="primary" @click="start">{{ game.status==='paused'?'继续飞行':game.status==='ready'?'开始 90 秒飞行':'再飞一局' }}</button></view>
      </view><button v-if="game.status==='running'" class="secondary pause" @click="pause">暂停，休息一下</button>
    </view><view class="flight-sidebar"><view class="card flight-brief"><text class="heading">飞行小手册</text><view class="brief-row"><text>01</text><view><text>手指带路</text><text>按住并移动。飞机跟着你走，不用一直点发射。</text></view></view><view class="brief-row"><text>02</text><view><text>观察空隙</text><text>小飞机一击消除，大飞机需要四击。橙色小点是敌方子弹。</text></view></view><view class="brief-row"><text>03</text><view><text>接住补给</text><text>绿色「盾」抵挡一次碰撞，黄色「三」带来 8 秒三路发射。</text></view></view><view class="best-score"><text>本机最高分</text><text>{{ best || '第一次起飞，等你创造' }}</text></view></view>
    <view class="card"><text class="heading">也可以用方向按钮</text><view class="direction-pad"><button class="secondary up" aria-label="上移" @click="nudge(0,-24)">↑</button><button class="secondary" aria-label="左移" @click="nudge(-24,0)">←</button><button class="secondary" aria-label="下移" @click="nudge(0,24)">↓</button><button class="secondary" aria-label="右移" @click="nudge(24,0)">→</button></view><text class="muted break-note">一局最多 90 秒。结束后停下来，和家长聊聊刚才最巧妙的一次避让。</text></view><text v-if="error" class="error">{{ error }}</text></view></view>
  </view>
</template>
<script>
import { createPlane, stepPlane, movePlane, touchPosition } from '@/game/plane.mjs'
import { drawPlane } from '@/game/plane-draw.mjs'
import { arcadeStore } from '@/services/arcade.js'
import { bestText } from '@/game/arcade-progress.mjs'
export default {
  data(){return {game:createPlane(),width:300,height:450,rect:null,timer:null,resizeTimer:null,last:0,dragging:false,best:'',error:''}},
  computed:{statusTitle(){return {ready:'飞行员，请就位',paused:'让眼睛歇一歇',over:'这一局，辛苦啦',complete:'90 秒飞行完成！'}[this.game.status]},statusCopy(){return ['over','complete'].includes(this.game.status)?`获得 ${this.game.score} 分 · 可以休息，也可以再挑战`:'3 次机会 · 自动发射 · 随时暂停'}},
  onReady(){this.measure();try{this.best=bestText(arcadeStore.read(),'plane')}catch(e){this.error=e.message}},onShow(){if(this.rect)this.$nextTick(this.measure)},onResize(){this.$nextTick(this.measure)},onHide(){this.pause()},onUnload(){this.stop()},
  methods:{
    measure(){uni.createSelectorQuery().in(this).select('.battle-column').boundingClientRect(r=>{if(!r)return;const info=uni.getSystemInfoSync();this.width=Math.floor(Math.max(180,Math.min(420,r.width,Math.max(180,(info.windowHeight-320)/1.5))));this.height=Math.round(this.width*1.5);this.$nextTick(()=>{uni.createSelectorQuery().in(this).select('#plane-stage').boundingClientRect(rect=>{this.rect=rect;clearTimeout(this.resizeTimer);this.resizeTimer=setTimeout(this.draw,100)}).exec()})}).exec()},
    draw(){const c=uni.createCanvasContext('plane-stage',this);c.scale(this.width/320,this.height/480);drawPlane(c,this.game);c.draw()},
    start(){this.stop();if(this.game.status!=='paused')this.game=createPlane();this.game.status='running';this.last=Date.now();this.timer=setInterval(()=>{const now=Date.now();stepPlane(this.game,(now-this.last)/1000);this.last=now;this.draw();if(this.game.status!=='running'){this.stop();this.save()}},33);this.draw()},
    stop(){clearTimeout(this.resizeTimer);clearInterval(this.timer);this.timer=null;this.dragging=false},pause(){this.stop();if(this.game.status==='running')this.game.status='paused'},
    touch(event){if(this.game.status!=='running'||!this.rect)return;const t=event.touches&&event.touches[0];if(!t)return;const p=touchPosition(t,this.rect);movePlane(this.game,p.x,p.y)},
    mouseDown(event){this.dragging=true;this.mouseMove(event)},mouseMove(event){if(!this.dragging||this.game.status!=='running'||!this.rect)return;const p=touchPosition(Number.isFinite(event.offsetX)?{x:event.offsetX,y:event.offsetY}:{clientX:event.clientX,clientY:event.clientY},this.rect);movePlane(this.game,p.x,p.y)},
    nudge(x,y){if(this.game.status!=='running')return;movePlane(this.game,this.game.player.x+x,this.game.player.y+y)},
    save(){try{this.best=bestText(arcadeStore.save('plane',this.game.score,Date.now()),'plane');this.error=''}catch(e){this.error=e.message}}
  }
}
</script>
<style src="@/styles/family.css"></style>
<style scoped>
.plane-page{background:#f0f5f6}.plane-heading{display:flex;align-items:center;justify-content:space-between;gap:16px}.plane-heading .title{color:#285566}.pilot-mark{font-size:65px;color:#4b8e96;transform:rotate(-15deg)}.flight-stats{display:flex;justify-content:space-between;gap:8px;padding:15px;background:#244c60;border-radius:18px 18px 0 0;color:#fff;max-width:420px;margin:auto;box-sizing:border-box}.flight-stats>view{text-align:center;flex:1}.flight-stats text{display:block;font-size:10px;color:#bcd1da}.flight-stats text:last-child{font-size:19px;color:#fff;margin-top:5px;font-weight:650}.battle-wrap{position:relative;margin:0 auto;border-radius:0 0 18px 18px;overflow:hidden;box-shadow:0 8px 20px #243f5414}.battle{display:block;touch-action:none}.flight-overlay{position:absolute;inset:0;background:#e8f0f0ed;display:flex;align-items:center;justify-content:center;flex-direction:column;padding:23px;box-sizing:border-box;text-align:center}.overlay-emblem{font-size:60px;color:#438792;margin-bottom:18px}.overlay-title{font-size:23px;font-weight:650;color:#285366}.overlay-copy{font-size:12px;color:#587583;margin:18px 0 25px;line-height:1.9}.flight-overlay .primary{width:100%;max-width:240px;background:#327c8e;border-color:#2b6a7f}.pause{margin:16px auto 22px;max-width:420px}.flight-sidebar{margin-top:22px;min-width:0}.brief-row{display:flex;gap:13px;margin:20px 0}.brief-row>text{font-size:19px;color:#7aadb0}.brief-row view{flex:1}.brief-row view text{display:block;font-size:14px;color:#345968;line-height:1.8}.brief-row view text:last-child{color:#6b8490;font-size:12px;margin-top:4px}.best-score{padding:15px;background:#e8f4f0;border-radius:12px}.best-score text{display:block;font-size:11px;color:#577c70}.best-score text:last-child{font-size:18px;color:#347d6b;margin-top:5px}.direction-pad{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;max-width:250px;margin:0 auto}.direction-pad button{margin:0;width:100%;font-size:21px}.direction-pad .up{grid-column:2}.direction-pad button:nth-child(2){grid-column:1}.break-note{margin-top:18px;font-size:12px}
@media(min-width:768px){.flight-layout{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(270px,1fr);gap:28px}.flight-sidebar{margin-top:0}.plane-heading{margin-bottom:15px}.flight-brief{padding:25px}.brief-row view text:last-child{font-size:14px}}
</style>
